### ISSUE TITLE
LABS Proposal

### ISSUE THREAD

**Issue by ghost** [StakedChain/StakedNotary#22]
### KMD LABS: Proposal

LABS Main Chain:

    51% PoS 49% PoW - Equihash, same as KMD.

    ac_founders=1440 - Pays notary node multisig address every 24H 33% of the supply split between all nodes, based on notarisation counts. (33% up to discussion, we need notaries to not collude to inflate supply.)

    Eventually we need some way of making sure all notary nodes are not too close together. This is a hard problem to solve.

    1 KMD notary node at least to pay for KMD notarisations cost. More than one, each with a single operator is better.

    blackjok3r, Alright, smk762 have all commited to running for KMD notary election.

    Bounty Program:

        Alright: Put bounty info here. nou

LABS is fungible with all chains in the LABS cluster. You can send LABS coins to any working LABS chain at any time using MoMoM. 
    
Fungible LABS chains:

    60% PoS 40% PoW - VerusHashV2 with PoS64. 

    0 Block reward apart from transaction fees.

    These chains due to their PoS component require ~20,000-50,000 LABS to create. (this may need adjustment)

    There must always be a supply of coins being staked on these chains to keep them moving. PoW can be done to unstick a chain if need be.

    Anyone using these chains should be able to stake/CPU mine on them when using it for testing or contracts or whatever needed. 

    When a chain stops for X (64?) days, it is considered dead. Any supply left on it is burnt. 

    Notaries must remove the dead chains and a copy of them will be backed up to the LABSMETA chain using the streamer.

Non Fungible LAB Chains:

    Any combination of whatever as params. These chains are for testing consensus changes that may break the cluster.

    Chains free to create but have dPoW cost, this needs to be definitively decided. I think maybe ~1000 LABS per chain? paid split to each notary that adds them.

    These chains may be short lived or long, if proven stable they can be added as a Fungible chain after being tested (with new supply).

    There is no need to backup these chains unless needed for data collection. Or something cool that happened ;)

    
CFEK Chains:

    Designed to be broken. Cost maybe even 0. Used before making a LAB chain.

    Likey where maybe bounties are paid from? 

LABS notaries (19):
-     Alright
-     jorian
-     greentea
-     zatJUM
-     gcharang
-     blackjok3r
-     computergenie
-     CMaurice
-     CrisF
-     smk
-     SHossain
-     metaphilibert
-     Bar_F1sh_Rel
-     TonyL
-     webworker01
-     dwy
-     nabob
-     daemonfox
-     CHMEX

**Comment by Alrighttt** [comment]
```
- dev launches LABS chain after initial CFEK testing
- dev encourages testers to test it and users to cautiously use it
- tester finds a reproducible bug, documents it, makes a bounty claim("I think I deserve this much for finding this bug")
- notaries determine if the claim is fair
- if so, tester works with contract dev to fix it
- fix is validated
- a new fungible chain is created to add the coins into the cluster, coins are migrated to main chain then chain immediately dies
```
This is my proposed mechanism for bug bounties. We need to determine how we limit the amount of coins that can be created by these bounties. I think a sensible way of doing it would be to cap it at a percentage of weekly coin emissions. Possibly 0.5%/week.

EDIT: 
As discussed on discord just now,
`a new fungible chain is created to add the coins into the cluster, coins are migrated to main chain then chain immediately dies` this will not be the mechanism for creating these coins. The tentative plan is to have a fungible chain that pays out a set amount to the notary multisig. This means block reward on main chain will be reduced by the notary percentage, and this notary percentage along with bounty percentage will be off loaded to a separate chain. If there is no bounty claim for a given week(month?), the coins created to accommodate bounties will be burned via OP_RETURN. 

If we go this route, it allows us to easily change the signers of the multisig each time we change notaries.

**Comment by smk762** [comment]
optimal node spatial dispersion: track mean node ping. apply tiered reward multiplier for nodes with ping in standard deviation ranges around mean?

Formula for calculating maximum cable length in km by ping time is: ((latency_in_ms÷1000÷2)×3×10^8)÷1000 [km] 

`komodo-cli -acname=<COINTAG> getpeerinfo | jq '.[].pingtime'`

is there (or can we add) a flag to filter `getpeerinfo` for notaries only?

Chain starvation death and tombstone backup is nice. Does remaining supply have to be burnt, or can it be buried with the bones in case of future necromancy?

Suggest CFEK chains incur small fee to avoid abuse. Will coin tags be reusable? 
e.g
Fungible, ready for adoption: 20k LABS (Masters)
Non-fungible, in testing: 2k LABS (Acolytes)
CFEK, kill it with fire: 200 LABS (Initiates)

Personal use ac for testing on KMD already free, but CFEK would mean access to extra testers (Groupies) and help walking through it for Initiates. LABS is the club, there should be a door fee for players to allow rain for thirsty groupies. Initiates get in the lobby (chain), Acolytes get into the lounge (dPoW), Masters get VIP room (fungibility). 

Bug bounties:
Acolytes might have different allocations and targets, dont want to define it too restrictively. % of emissions is good baseline (via -ac_perc?). Acolyte might offer bonuses to bounty fund or directly to Groupie if reasons. 

Bounty fund:
Groupie applies or is nominated for bounty.
Notaries vote on value?
ratified by > 66% of notaries via multisig = paid.
application/nomination/vote/ratification/tx = stored in oracle.

**Comment by ghost** [comment]
Maybe some percentage of the notary funds goes toward bounties? This would make it a set capped amount, its ikely that notaries will be claiming bounties, so using the multi sig mechanism prevents abuse. This could become a time consuming job though. 
I would steer clear of creating new chains with note supply to pay bounties, build the fund directly into the coin emission. If they are not used at the end of each notary era the are burnt.

**Comment by Cris-F** [comment]
Hi, to help me get things clear about how the above (as of last night) would look for a new project coming to Labs I made a diagram.  There are some major points that need discussion, from what people have said, that I will need to change and add.  The diagram hopefully reflects how things stand, as written above.
https://postimg.cc/WD3xMRwX 
Please let me know what should be changed.  
(diagram only for new project flow, not other matters proposed above)

**Comment by TheComputerGenie** [comment]
Tentative agreement (still questionable about math, as discussed in discord).

I, also, will be running for KMD NN election this year (fwiw).
