### ISSUE TITLE
Vote can be changed  on VOTE TUI

### ISSUE THREAD

**Issue by Nagaws** [StakedChain/StakedNotary#28]
There are two polls, 

first i registered and voted CHMEX poll, There i have selected  "yes, mega cool" and after then sometime i have selected "yes" and Viewed results i can able to see results got changed

Operator : Nabob

{'Bar_F1sh_Rel': 'unanswered',
 'CHMEX': 'yes mega cool',
 'CMaurice': 'unanswered',
 'CrisF': 'yes mega cool',
 'Nabob': 'yes',
 'SHossain': 'unanswered',
 'TonyL': 'unanswered',
 'alright': 'FIXME oraclessamples bug or registered but did not vote yet',
 'blackjok3r': 'unanswered',
 'computergenie': 'unanswered',
 'daemonfox': 'unanswered',
 'dwy': 'unanswered',
 'gcharang': 'unanswered',
 'greentea': 'unanswered',
 'jorian': 'unanswered',
 'metaphilibert': 'unanswered',
 'mylo': 'unanswered',
 'smk762': 'unanswered',
 'webworker01': 'unanswered',
 'zatJUM': 'unanswered'}

**Comment by Alrighttt** [comment]
Could you provide the txid for the initial "yes, mega cool" oraclesdata?
