### ISSUE TITLE
Vote TUI: able to change vote on notary node poll (20/22) but with error

### ISSUE THREAD

**Issue by Nagaws** [StakedChain/StakedNotary#30]
Tried to change vote on NN poll, 

1) Tried to register and Voted on poll as "22"
2) After some time, voted to 20
3) Got error
Error: oraclesdata rpc command failed with {'error': 'couldnt find enough oracle inputs RUfPQUm83YMxZQuQacu81VckMtbD1gLXjj, limit 1 per utxo\n', 'result': 'error'}

4) when i register again and cast vote, can able to change vote to "20"

**Comment by Alrighttt** [comment]
You can vote as many times as you like, but it should not affect the results of the poll. Only the initial vote's value will matter. Is this not the case?

**Comment by Nagaws** [comment]
yes, after oracle data fail, result should not change, but when checked the vote result got changed to "20"
I have done couple of times vote change

**Comment by Alrighttt** [comment]
Could you change it to 20 right now? Are you sure you're running the latest version of NNvote.py?

I see your vote as 22 right now.

**Comment by Nagaws** [comment]
1a9f49cc836bfd618c398b49f70c3be53b25f4d17df5544dae7339d6cbb68f7f

changed to 20
