### ISSUE TITLE
Vote TUI: Getting loop error sometimes

### ISSUE THREAD

**Issue by Nagaws** [StakedChain/StakedNotary#32]
While, testing TUI  when selecting options Python script going into recursive loop

CFEKDRAGON_7776           LICENSE                   assetchains               config_example.ini        lib.py                    oraclefetch.sh            start_iguana.sh           utxosplitter.sh           
CFEKHOUND_7776            NNvote.py                 assetchains.json          dpowassets.py             listassetchainparams.py   oraclepush.sh             stats                     validateaddress.sh        
CFEKORC_7776              README.md                 assets-cli                dwy_attack_mitigation.sh  listassetchains.py        peer_ips.txt              stats.py                  walletreset.sh            
CFEKORKL_7776             TotalSupply.sh            build_iguana              iguana/                   listbranches.py           printkey.py               stop.sh                   
make a selection:
.git/                     CFEKPAY_7776              __pycache__/              checkmasks                install/                  listclis.sh               splitfunds.sh             update_komodo.sh          
.gitignore                LABSRCTEST_7776           asset-cli                 config.ini                komodo/                   listcoins.sh              start.sh                  updatefirewall.sh         
CFEKDRAGON_7776           LICENSE                   assetchains               config_example.ini        lib.py                    oraclefetch.sh            start_iguana.sh           utxosplitter.sh           
CFEKHOUND_7776            NNvote.py                 assetchains.json          dpowassets.py             listassetchainparams.py   oraclepush.sh             stats                     validateaddress.sh        
CFEKORC_7776              README.md                 assets-cli                dwy_attack_mitigation.sh  listassetchains.py        peer_ips.txt              stats.py                  walletreset.sh            
CFEKORKL_7776             TotalSupply.sh            build_iguana              iguana/                   listbranches.py           printkey.py               stop.sh                   
make a selection:
.git/                     CFEKPAY_7776              __pycache__/              checkmasks                install/                  listclis.sh               splitfunds.sh             update_komodo.sh          
.gitignore                LABSRCTEST_7776           asset-cli                 config.ini                komodo/                   listcoins.sh              start.sh                  updatefirewall.sh         
CFEKDRAGON_7776           LICENSE                   assetchains               config_example.ini        lib.py                    oraclefetch.sh            start_iguana.sh           utxosplitter.sh           
CFEKHOUND_7776            NNvote.py                 assetchains.json          dpowassets.py             listassetchainparams.py   oraclepush.sh             stats                     validateaddress.sh        
CFEKORC_7776              README.md                 assets-cli                dwy_attack_mitigation.sh  listassetchains.py        peer_ips.txt              stats.py                  walletreset.sh            
CFEKORKL_7776             TotalSupply.sh            build_iguana              iguana/                   listbranches.py           printkey.py               stop.sh                   
make a selection:
.git/                     CFEKPAY_7776              __pycache__/              checkmasks                install/                  listclis.sh               splitfunds.sh             update_komodo.sh          
.gitignore                LABSRCTEST_7776           asset-cli                 config.ini                komodo/                   listcoins.sh              start.sh                  updatefirewall.sh         
CFEKDRAGON_7776           LICENSE                   assetchains               config_example.ini        lib.py                    oraclefetch.sh            start_iguana.sh           utxosplitter.sh           
CFEKHOUND_7776            NNvote.py                 assetchains.json          dpowassets.py             listassetchainparams.py   oraclepush.sh             stats                     validateaddress.sh        
CFEKORC_7776              README.md                 assets-cli                dwy_attack_mitigation.sh  listassetchains.py        peer_ips.txt              stats.py                  walletreset.sh            
CFEKORKL_7776             TotalSupply.sh            build_iguana              iguana/                   listbranches.py           printkey.py               stop.sh                   
make a selection:
.git/                     CFEKPAY_7776              __pycache__/              checkmasks                install/                  listclis.sh               splitfunds.sh             update_komodo.sh          
.gitignore                LABSRCTEST_7776           asset-cli                 config.ini                komodo/                   listcoins.sh              start.sh                  updatefirewall.sh         
CFEKDRAGON_7776           LICENSE                   assetchains               config_example.ini        lib.py                    oraclefetch.sh            start_iguana.sh           utxosplitter.sh           
CFEKHOUND_7776            NNvote.py                 assetchains.json          dpowassets.py             listassetchainparams.py   oraclepush.sh             stats                     validateaddress.sh        
CFEKORC_7776              README.md                 assets-cli                dwy_attack_mitigation.sh  listassetchains.py        peer_ips.txt              stats.py                  walletreset.sh            
CFEKORKL_7776             TotalSupply.sh            build_iguana              iguana/                   listbranches.py           printkey.py               stop.sh                   
make a selection:Traceback (most recent call last):
  File "./NNvote.py", line 93, in <module>
    vote_loop('CFEKORC', '')
  File "./NNvote.py", line 55, in vote_loop
    msg = vote_selection(chain, '', 'vote')
  File "./NNvote.py", line 74, in vote_selection
    msg = option_selection(chain, active_polls[selection])
  File "./NNvote.py", line 89, in option_selection
    vote_loop(chain, msg)
  File "./NNvote.py", line 52, in vote_loop
    msg = vote_selection(chain, '', 'register')
  File "./NNvote.py", line 79, in vote_selection
    vote_loop(chain, msg)
  File "./NNvote.py", line 50, in vote_loop
    vote_loop(chain, msg)
  File "./NNvote.py", line 58, in vote_loop
    msg = vote_selection(chain, '', 'view results')
  File "./NNvote.py", line 79, in vote_selection
    vote_loop(chain, msg)
  File "./NNvote.py", line 50, in vote_loop
    vote_loop(chain, msg)
  File "./NNvote.py", line 55, in vote_loop
    msg = vote_selection(chain, '', 'vote')
  File "./NNvote.py", line 74, in vote_selection
    msg = option_selection(chain, active_polls[selection])
  File "./NNvote.py", line 89, in option_selection
    vote_loop(chain, msg)
  File "./NNvote.py", line 52, in vote_loop
    msg = vote_selection(chain, '', 'register')
  File "./NNvote.py", line 79, in vote_selection
    vote_loop(chain, msg)
  File "./NNvote.py", line 55, in vote_loop
    msg = vote_selection(chain, '', 'vote')
  File "./NNvote.py", line 74, in vote_selection
    msg = option_selection(chain, active_polls[selection])
  File "./NNvote.py", line 89, in option_selection
    vote_loop(chain, msg)
  File "./NNvote.py", line 55, in vote_loop
    msg = vote_selection(chain, '', 'vote')
  File "./NNvote.py", line 74, in vote_selection
    msg = option_selection(chain, active_polls[selection])
  File "./NNvote.py", line 89, in option_selection
    vote_loop(chain, msg)
  File "./NNvote.py", line 52, in vote_loop
    msg = vote_selection(chain, '', 'register')
  File "./NNvote.py", line 79, in vote_selection
    vote_loop(chain, msg)
  File "./NNvote.py", line 55, in vote_loop
    msg = vote_selection(chain, '', 'vote')
  File "./NNvote.py", line 72, in vote_selection
    selection = lib.user_inputInt(0,len(active_polls)-1,"make a selection:")
  File "/home/staked/StakedNotary/lib.py", line 93, in user_inputInt
    user_input = input(msg)
KeyboardInterrupt

**Comment by Alrighttt** [comment]
Could you provide the steps necessary to reproduce this please?

**Comment by Nagaws** [comment]
this issue is intermittent, not sure how to reproduce

**Comment by smk762** [comment]
Closing issue as no update recently.
