### ISSUE TITLE
error when pip3 install slick-bitcoinrp

### ISSUE THREAD

**Issue by NOCTLJRNE** [StakedChain/StakedNotary#40]
how to reproduce : on Ubuntu 16.04 LTS fresh image.
follow the StakedNotary Install instructions:
pip3 install slick-bitcoinrpc    
will return this error 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u50s12lk/pycurl/
the package below must be installed to resolve this error:
sudo apt-get install libcurl4-gnutls-dev

**Comment by smk762** [comment]
I assume this was resolved by running ` sudo apt-get install libcurl4-gnutls-dev` ?

**Comment by phm87** [comment]
Can we adapt the Readme ? I also encountered this error (arm64, ubuntu 19.10) and installing the package libcurl4-gnutls-dev fixed it. Thank you

**Comment by smk762** [comment]
done
